config/routes.rb
Rails.application.routes.draw do

  get 'book_cab/:user_id' => 'cab#book_cab', as: :book_cab
  get 'end_ride/:user_id' => 'cab#end_ride', as: :end_ride
  get 'show' => 'cab#show'
 

end

app/models/cab.rb
class Cab < ActiveRecord::Base
  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude
  belongs_to :user     
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :cab
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cab_controller.rb
class CabController < ApplicationController

  def book_cab
    cab = Cab.where(:user_id => params[:user_id])
    if cab.blank?
      location = getlocation()
      cab = find_nearest_cab(location)
    else
      render :end_ride
    end
  end
  
  def getlocation()
    latitude = rand()*10 + 25.32
    longitude = rand()*10 + 68.00
    [latitude, longitude]
  end
  
  def find_nearest_cab(location)
    cab = Cab.where(:status => "unreserved").closest(origin: location).first
    if cab.blank?
      render :no_cab
    else
      @cab = cab.update_attributes(:status => "booked", :user_id => params[:user_id], :latitude => location[0], :longitude => location[1])
      render :book_cab
    end
  end
  
  def end_ride
    user_id = params[:user_id]
    cab = Cab.find_by(:user_id => user_id)
    cab.update_attributes(:status => "unreserved", :user_id => nil)
    render :book_cab
  end
  
  def show
    @unreserved_cab = Cab.where(:status => "unreserved")
    @booked_cab = Cab.where(:status => "booked")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cab_helper.rb
module CabHelper
end

app/views/cab/book_cab.html.erb
<%= button_to 'Start Ride', book_cab_path, method: :get  %>

app/views/cab/end_ride.html.erb
Your ride has started please click on end ride to end your ride
<%= button_to 'End Ride', end_ride_path, method: :get%>

app/views/cab/no_cab.html.erb
sorry no cabs available at the moment

app/views/cab/show.html.erb
<%= "List of unreserved  cabs" %>
<br />
<% @unreserved_cab.each do |cab|%>
  <%= cab.number %>
  <%= cab.color %>
  <br />
<% end %>

<%= "List of booked cabs" %>
<br />
<% @booked_cab.each do |cab|%>
  <%= cab.number %>
  <%= cab.color %>
  <%= cab.user.name %>
  <br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaxiOnDemand</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>